name: stock_management_mobile
description: Mobile application for Stock Management System
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Navigation
  go_router: ^13.0.0

  # HTTP & API
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.10

  # UI Components
  flutter_material_ui: ^1.0.0
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0

  # Utils
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  permission_handler: ^11.2.0
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.1

  # Camera & Barcode
  camera: ^0.10.5+7
  qr_code_scanner: ^1.0.1
  barcode_widget: ^2.0.3

  # Charts & Analytics
  fl_chart: ^0.65.0
  syncfusion_flutter_charts: ^24.1.41

  # File handling
  file_picker: ^6.1.1
  path_provider: ^2.1.2
  csv: ^5.0.2
  pdf: ^3.10.7

  # Local Database
  sqflite: ^2.3.0
  drift: ^2.14.1

  # Image handling
  image_picker: ^1.0.5
  image_cropper: ^5.0.1

  # Form validation
  formz: ^0.6.1

  # Animations
  lottie: ^2.7.0
  rive: ^0.12.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1
  drift_dev: ^2.14.1

  # Linting
  flutter_lints: ^3.0.1

  # Testing
  bloc_test: ^9.1.5
  mocktail: ^1.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/data/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700